### ISSUE TITLE
How to support angular inline styles

### ISSUE THREAD

**Issue by anoopsinghbayes** [ota-meshi/postcss-html#109]
This is a great library ,
i would like to to know if this can support angular  inline styles
check this syntax for angular component
```
@Component({
  selector: 'app-root',
  template: `
    <h1>Tour of Heroes</h1>
    <app-hero-main [hero]="hero"></app-hero-main>
  `,
  styles: ['h1 { font-weight: normal; }']
})
export class HeroAppComponent {
/* . . . */
}
```
https://angular.io/guide/component-styles
angular component inline styles are defined as a property styles defined on @component decorator inside a ts file

**Comment by anoopsinghbayes** [comment]
never mind i found another plugin that does it for angular , this issue can be closed.

**Comment by ota-meshi** [comment]
Thank you for posting this issue.
I'm not familiar with Angular so I don't know if it can be done well.
Based on the link you provided, I don't think it can be supported as it doesn't have a syntax similar to HTML.
