### ISSUE TITLE
<style lang="scss"> not effect

### ISSUE THREAD

**Issue by hangaoke1** [ota-meshi/postcss-html#24]
![image](https://user-images.githubusercontent.com/19623160/139656651-babf931e-6690-4898-a99a-4f4990be8aa7.png)

```js
module.exports = {
  extends: ['stylelint-config-standard'],
  plugins: ['stylelint-order'],
  overrides: [
    {
      files: ['*.html', '**/*.html', '**/*.vue'],
      customSyntax: 'postcss-html',
    },
  ],
  rules: {
    'order/properties-order': [
      'position',
      'top',
      'right',
      'bottom',
      'left',
      'z-index',
      'display',
      'justify-content',
      'align-items',
      'float',
      'clear',
      'overflow',
      'overflow-x',
      'overflow-y',
      'width',
      'min-width',
      'max-width',
      'height',
      'min-height',
      'max-height',
      'padding',
      'padding-top',
      'padding-right',
      'padding-bottom',
      'padding-left',
      'margin',
      'margin-top',
      'margin-right',
      'margin-bottom',
      'margin-left',
      'font-size',
      'font-family',
      'font-weight',
      'text-align',
      'text-justify',
      'text-indent',
      'text-overflow',
      'text-decoration',
      'white-space',
      'color',
      'border',
      'border-style',
      'border-width',
      'border-color',
      'border-top',
      'border-top-style',
      'border-top-width',
      'border-top-color',
      'border-right',
      'border-right-style',
      'border-right-width',
      'border-right-color',
      'border-bottom',
      'border-bottom-style',
      'border-bottom-width',
      'border-bottom-color',
      'border-left',
      'border-left-style',
      'border-left-width',
      'border-left-color',
      'border-radius',
      'background',
      'background-position',
      'background-repeat',
      'background-size',
      'background-color',
      'background-clip',
      'opacity',
      'filter',
      'list-style',
      'outline',
      'visibility',
      'box-shadow',
      'text-shadow',
      'resize',
      'transition',
    ],
  },
}

```

**Comment by hangaoke1** [comment]
I install the postcss-scss@4.0.2

**Comment by ota-meshi** [comment]
Could you share your repository that can reproduce your problem?

**Comment by hangaoke1** [comment]
https://github.com/hangaoke1/postcss-html-issue , the problem is happen in Visual Studio Code 1.61.2 , and
 ![image](https://user-images.githubusercontent.com/19623160/139671614-07f511d4-2985-4e0e-91d0-34b1e79a472b.png)

![image](https://user-images.githubusercontent.com/19623160/139671703-9ced3ce9-a0d3-4a2b-8454-6c3a29f119f7.png)

**Comment by ota-meshi** [comment]
It looks like postcss-scss is not installed.

https://github.com/hangaoke1/postcss-html-issue/blob/master/package.json
https://github.com/hangaoke1/postcss-html-issue/blob/master/package-lock.json

> I install the postcss-scss@4.0.2

Where did you install it?

**Comment by ota-meshi** [comment]
It looks like it works fine if you install postcss-scss.

![image](https://user-images.githubusercontent.com/16508807/139675268-55f56a26-76d4-4ce3-8d95-5bca962b7b63.png)

**Comment by hangaoke1** [comment]
it's strange i install the postcss-scss ， but still has the problem，maybe is some problem in my dev environment
![image](https://user-images.githubusercontent.com/19623160/139675704-2dd6cb4e-2d60-4ad3-8b4f-26192560b191.png)

![image](https://user-images.githubusercontent.com/19623160/139675750-d0e16a4a-501f-4144-b614-ed29f95f9035.png)

**Comment by hangaoke1** [comment]
It may be a problem with mac m1

**Comment by ota-meshi** [comment]
Restarting VS Code after installation may resolve the issue.

**Comment by hangaoke1** [comment]
my mistake，after install the dependency，need to restart the vscode 😂
