### ISSUE TITLE
Official Svelte Support

### ISSUE THREAD

**Issue by FractalHQ** [ota-meshi/postcss-html#33]
Hey there!  I've been struggling with getting Svelte working in VS-Code again since stylelint v14.  It would be great to have some official support for Svelte, or perhaps just a section in the docs for any Svelte-specific instructions.  If I can figure this out, I'll try to make a PR if appropriate.  Thanks!!

**Comment by ota-meshi** [comment]
Thank you for posting this issue.
What did you struggle with? I think it works well in most cases just by setting the following:

```json
{
    "overrides": [
        {
            "files": ["*.svelte", "**/*.svelte"],
            "customSyntax": "postcss-html"
        }
    ]
}
```

**Comment by ota-meshi** [comment]
I'm not sure what documentation you need. If you can write the documentation need for Svelte users, please open a PR in this repository.
