### ISSUE TITLE
Ignore `style="..."` attributes

### ISSUE THREAD

**Issue by james-camilleri** [ota-meshi/postcss-html#38]
I couldn't find any information about this anywhere, so I might be missing something obvious - sorry if that's the case.

Is there any way to have the parser handle `<style>` tags but not `<div style="...">` attributes? I've set this up with a Svelte project, and while the linting is working as I'd hoped in my main style tags, it seems a bit bizarre for the linter to flag things like "Expected empty line before custom property" in a single-line style attribute.

Is there an option that can be configured, or have I messed up some default? And if not, is it something that could be corrected?

Thanks!

**Comment by ota-meshi** [comment]
Thank you for posting this issue.

I'm not sure if we need to add that ignore `style="..."` option.
The custom-property-empty-line-before rule has an option to ignore a single line.
https://stylelint.io/user-guide/rules/list/custom-property-empty-line-before#inside-single-line-block
Why can't you use it?

Also, can't you use `<!-- postcss-ignore -->` comments?
https://github.com/ota-meshi/postcss-html#turning-postcss-off-from-within-your-html

**Comment by james-camilleri** [comment]
Hi! Thanks for getting back to me on this. I didn't know about the single line rule, that will probably fix this particular scenario. I'll give it a shot. I'm not sure if there are any other scenarios where this option would come in handy, so perhaps I should close the ticket and reopen it if I run into any other scenarios?

**Comment by ota-meshi** [comment]
I don't think we need the option to ignore the attribute.  If you think need it, open a new issue and explain in detail why you need it.

**Comment by mattosborn** [comment]
> I'm not sure if we need to add that ignore `style="..."` option. The custom-property-empty-line-before rule has an option to ignore a single line. https://stylelint.io/user-guide/rules/list/custom-property-empty-line-before#inside-single-line-block Why can't you use it?

It looks like these exceptions don't work correctly for inline svelte `style` attributes. My guess is inline css isn't being seen as a `single-line-block` as far as the linter is concerned. For example with the following rule config:

```json
"custom-property-empty-line-before": "always"
```

This throws two errors:

<img width="437" alt="image" src="https://user-images.githubusercontent.com/960919/213735960-0b8b10dd-0583-46f6-8a59-10c39188a5ec.png">

I'd expect the following config to fix these errors (actually just the `ignore` should do it really?):

```json
"custom-property-empty-line-before": [
  "always",
  {
    "except": [ "first-nested" ],
    "ignore": [ "inside-single-line-block" ]
  }
]
```

But it has no effect. Adding `"after-custom-property"` to `except` disables the second error, so the parser is picking up the config. 

The only two options I can see for svelte projects are:
1. Disable the rule entirely
2. Wrap offending elements in `<!-- postcss-ignore -->`

Neither of which are ideal
