### ISSUE TITLE
webpack error

### ISSUE THREAD

**Issue by YangLG-7** [ota-meshi/postcss-html#43]
I couldn't find any information about this anywhere, so I might be missing something obvious - sorry if that's the case.

I use `postcss-html` to parse html content to get style tag . But when I used webpack to package, an exception occurred

```
  "devDependencies": {
    "webpack": "^5.70.0",
    "webpack-cli": "^4.9.2"
  },
  "dependencies": {
    "postcss": "^8.4.12",
    "postcss-html": "^1.3.0"
  }
```

the code like
```
const postcss = require('postcss');
const syntax = require('postcss-html')({});

const source = `
<template>
    <div>1</div>
</template>
<script>
</script>
<style>
  .a{
    color:red
  }
</style>
<style>
  .b{
    color:red
  }
</style>
`
async function a(){
    const {root} = await postcss().process(source, { syntax })
    root.walkDecls('color', (del) => {
        console.log(del)
    })
}
a()
```

the webpack.config.js
```
const path = require('path');
module.exports = {
	entry: './index.js',
	mode: 'production',
	output: {
		filename: 'extension.js',
		path: path.join(__dirname, 'out')
	}
}
```

the error
```
Module not found: Error: Can't resolve 'postcss-sass' 
Module not found: Error: Can't resolve 'postcss-scss' 
Module not found: Error: Can't resolve 'postcss-less'
Module not found: Error: Can't resolve 'sugarss' 
Module not found: Error: Can't resolve 'postcss-styl'
```

Under webpack, the dependencies here will be checked?

https://github.com/ota-meshi/postcss-html/blob/befcb4ec3beeaf8f03389cc022f491389be9f441/lib/syntax/build-syntax-resolver.js#L94

**Comment by ota-meshi** [comment]
Thank you for posting the issue.
However, this package is not designed to work with browsers or bundles.
Even if you can solve it with your webpack settings, I don't know if it will work in future version upgrades.
