### ISSUE TITLE
Svelte: parser hangs on svelte assignment syntax

### ISSUE THREAD

**Issue by jhwz** [ota-meshi/postcss-html#55]
Given the component:
```svelte
<label value={something} />

<style>
	label {
		/* styles go here */
	}
</style>
```

the parser hangs. This is a pretty basic Svelte component, I'm surprised this is happening?

If you take away the `value={something}`, the parser runs fine. 

I am using this with `stylelint`, so maybe something is going on there..!

**Comment by ota-meshi** [comment]
I can't reproduce your problem. Can you share a minimal repository to reproduce?

https://ota-meshi.github.io/postcss-html/#eJwtjkEOwjAMBL9i+VhV5F4VXsATcgnFbSK5McKmFYrydwjlttrZkbbgJHfCAUcON2LYAr/oXFRWspjyUsFdfPZ5VHsztWjHsLTozXXwIwqLQKQnQecaqV/FHQ72KA9LkhWHghplv8oU/sUcWKnHOTHlsLYjRmon3YiNsNYPDw05nA==

**Comment by jhwz** [comment]
Okay so I have no idea why, but the issue is with the eslint version in my environment.

If I have either `eslint` not installed, or `eslint > 8.0.0` then everything runs fine. If I have `eslint < 8.0.0` then it hangs. It
seems to actually be happening in the `htmlparser2` package somewhere. 

Sorry for creating the issue without much investigation!
